"""meta de margem de lucro por tenant

Revision ID: 063c7aa4b371
Revises: fb6acdd91454
Create Date: 2026-08-14 15:00:46.543008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063c7aa4b371'
down_revision = 'fb6acdd91454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        # server_default é obrigatório: a tabela já tem tenants, e NOT NULL sem
        # valor padrão falha na hora de preencher as linhas existentes.
        batch_op.add_column(
            sa.Column('margem_lucro', sa.Float(), nullable=False, server_default='60')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('margem_lucro')

    # ### end Alembic commands ###
