"""cobranca da saas: planos e mensalidades

Revision ID: 217eb945355e
Revises: 271b3b099740
Create Date: 2026-08-13 15:47:49.776024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217eb945355e'
down_revision = '271b3b099740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('preco_mensal', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_slug'), ['slug'], unique=True)

    op.create_table('cobranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('plano_slug', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provedor', sa.String(length=20), nullable=False),
    sa.Column('id_externo', sa.String(length=120), nullable=True),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=40), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'competencia', name='uq_cobranca_tenant_competencia')
    )
    with op.batch_alter_table('cobranca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobranca_competencia'), ['competencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobranca_id_externo'), ['id_externo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobranca_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobranca_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobranca_vencimento'), ['vencimento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cobranca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobranca_vencimento'))
        batch_op.drop_index(batch_op.f('ix_cobranca_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cobranca_status'))
        batch_op.drop_index(batch_op.f('ix_cobranca_id_externo'))
        batch_op.drop_index(batch_op.f('ix_cobranca_competencia'))

    op.drop_table('cobranca')
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_slug'))

    op.drop_table('plano')
    # ### end Alembic commands ###
