"""cupons, bairros de entrega e combo promocional

Revision ID: 271b3b099740
Revises: 4bc798ae0d6a
Create Date: 2026-08-13 10:08:40.209669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271b3b099740'
down_revision = '4bc798ae0d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairro_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('taxa', sa.Float(), nullable=False),
    sa.Column('prazo_adicional_min', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_bairro_tenant_nome')
    )
    with op.batch_alter_table('bairro_entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bairro_entrega_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('pedido_minimo', sa.Float(), nullable=False),
    sa.Column('limite_usos', sa.Integer(), nullable=False),
    sa.Column('usos_confirmados', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('permite_combo_promocional', sa.Boolean(), nullable=False),
    sa.Column('inicio_em', sa.DateTime(), nullable=True),
    sa.Column('fim_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_cupom_tenant_codigo')
    )
    with op.batch_alter_table('cupom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupom_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupom_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cupom_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('reservado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('liberado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cupom_uso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupom_uso_cupom_id'), ['cupom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupom_uso_pedido_id'), ['pedido_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cupom_uso_status'), ['status'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bairro_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cupom_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cupom_codigo', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_pedido_bairro_id'), ['bairro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_cupom_codigo'), ['cupom_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_cupom_id'), ['cupom_id'], unique=False)
        # FKs com nome explícito: o autogenerate deixa None, e o downgrade
        # correspondente (drop_constraint(None)) falharia.
        batch_op.create_foreign_key(
            "fk_pedido_bairro_id", 'bairro_entrega', ['bairro_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            "fk_pedido_cupom_id", 'cupom', ['cupom_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('produto', schema=None) as batch_op:
        # server_default obrigatório: a tabela já tem produtos, e NOT NULL sem
        # default no banco é recusado pelo SQLite. Produtos existentes entram
        # como não-promocionais, que é o comportamento anterior.
        batch_op.add_column(
            sa.Column('combo_promocional', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('combo_promocional')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint("fk_pedido_cupom_id", type_='foreignkey')
        batch_op.drop_constraint("fk_pedido_bairro_id", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pedido_cupom_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_cupom_codigo'))
        batch_op.drop_index(batch_op.f('ix_pedido_bairro_id'))
        batch_op.drop_column('cupom_codigo')
        batch_op.drop_column('cupom_id')
        batch_op.drop_column('bairro_nome')
        batch_op.drop_column('bairro_id')

    with op.batch_alter_table('cupom_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupom_uso_status'))
        batch_op.drop_index(batch_op.f('ix_cupom_uso_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_cupom_uso_cupom_id'))

    op.drop_table('cupom_uso')
    with op.batch_alter_table('cupom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupom_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cupom_codigo'))

    op.drop_table('cupom')
    with op.batch_alter_table('bairro_entrega', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bairro_entrega_tenant_id'))

    op.drop_table('bairro_entrega')
    # ### end Alembic commands ###
