"""passe de suporte

Revision ID: 3f196c4fe4b6
Revises: 9e04a8f0bd1f
Create Date: 2026-08-21 16:05:41.431623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f196c4fe4b6'
down_revision = '9e04a8f0bd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passe_suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.String(length=80), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passe_suporte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passe_suporte_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passe_suporte_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passe_suporte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passe_suporte_token_hash'))
        batch_op.drop_index(batch_op.f('ix_passe_suporte_tenant_id'))

    op.drop_table('passe_suporte')
    # ### end Alembic commands ###
