"""agente de impressao e fila de comandas

Revision ID: 4044254d344a
Revises: 225eba0f4d3d
Create Date: 2026-08-20 16:56:42.398386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4044254d344a'
down_revision = '225eba0f4d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agente_impressao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('impressora', sa.String(length=255), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('ultimo_contato', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_agente_tenant')
    )
    with op.batch_alter_table('agente_impressao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agente_impressao_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agente_impressao_token_hash'), ['token_hash'], unique=False)

    op.create_table('impressao_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.String(length=500), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('reservado_em', sa.DateTime(), nullable=True),
    sa.Column('impresso_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impressao_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impressao_job_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_impressao_job_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impressao_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_impressao_job_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impressao_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impressao_job_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_impressao_job_status'))
        batch_op.drop_index(batch_op.f('ix_impressao_job_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_impressao_job_criado_em'))

    op.drop_table('impressao_job')
    with op.batch_alter_table('agente_impressao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agente_impressao_token_hash'))
        batch_op.drop_index(batch_op.f('ix_agente_impressao_tenant_id'))

    op.drop_table('agente_impressao')
    # ### end Alembic commands ###
