"""estoque: insumo, ficha tecnica, movimentacao e custo no pedido

Revision ID: 413201f851c5
Revises: 7bb574e2588f
Create Date: 2026-08-14 09:16:35.369926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413201f851c5'
down_revision = '7bb574e2588f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('preco_compra', sa.Float(), nullable=False),
    sa.Column('quantidade_compra', sa.Float(), nullable=False),
    sa.Column('estoque_atual', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=False),
    sa.Column('controle_estoque', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_insumo_tenant_nome')
    )
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insumo_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ficha_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'insumo_id', name='uq_ficha_produto_insumo')
    )
    with op.batch_alter_table('ficha_tecnica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ficha_tecnica_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ficha_tecnica_produto_id'), ['produto_id'], unique=False)

    op.create_table('movimentacao_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('saldo_anterior', sa.Float(), nullable=False),
    sa.Column('saldo_posterior', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=250), nullable=True),
    sa.Column('usuario', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id', 'insumo_id', 'tipo', name='uq_movimento_pedido_insumo_tipo')
    )
    with op.batch_alter_table('movimentacao_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacao_estoque_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_estoque_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_estoque_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_estoque_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_estoque_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        # server_default obrigatório: NOT NULL sem default no banco é recusado
        # em tabela com dados. Pedido anterior a esta fase entra com custo zero e
        # sem baixa — correto, porque não havia ficha técnica quando foi vendido.
        batch_op.add_column(
            sa.Column('custo_produtos', sa.Float(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('lucro_bruto', sa.Float(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('estoque_baixado', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_pedido_estoque_baixado'), ['estoque_baixado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_estoque_baixado'))
        batch_op.drop_column('estoque_baixado')
        batch_op.drop_column('lucro_bruto')
        batch_op.drop_column('custo_produtos')

    with op.batch_alter_table('movimentacao_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacao_estoque_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_estoque_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_estoque_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_estoque_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_estoque_created_at'))

    op.drop_table('movimentacao_estoque')
    with op.batch_alter_table('ficha_tecnica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ficha_tecnica_produto_id'))
        batch_op.drop_index(batch_op.f('ix_ficha_tecnica_insumo_id'))

    op.drop_table('ficha_tecnica')
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insumo_tenant_id'))

    op.drop_table('insumo')
    # ### end Alembic commands ###
