"""cardapio: categoria, adicional e campos do produto

Revision ID: 449ddaca9c75
Revises: e3f0dcfee1c2
Create Date: 2026-08-13 08:51:40.748357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449ddaca9c75'
down_revision = 'e3f0dcfee1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adicional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_adicional_tenant_nome')
    )
    with op.batch_alter_table('adicional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adicional_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_categoria_tenant_nome')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('produto_adicional',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('adicional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adicional_id'], ['adicional.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('produto_id', 'adicional_id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_produto_categoria_id'), ['categoria_id'], unique=False)
        # A FK precisa de nome explícito: o autogenerate deixa None aqui, e o
        # downgrade correspondente (drop_constraint(None)) falharia.
        batch_op.create_foreign_key(
            "fk_produto_categoria_id", 'categoria', ['categoria_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint("fk_produto_categoria_id", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_produto_categoria_id'))
        batch_op.drop_column('imagem')
        batch_op.drop_column('categoria_id')

    op.drop_table('produto_adicional')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_tenant_id'))

    op.drop_table('categoria')
    with op.batch_alter_table('adicional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adicional_tenant_id'))

    op.drop_table('adicional')
    # ### end Alembic commands ###
