"""pedidos: pedido, itens, adicionais do item e config de mesa

Revision ID: 4bc798ae0d6a
Revises: 449ddaca9c75
Create Date: 2026-08-13 09:17:23.247768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc798ae0d6a'
down_revision = '449ddaca9c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('mesa', sa.Integer(), nullable=True),
    sa.Column('comanda_aberta', sa.Boolean(), nullable=False),
    sa.Column('endereco', sa.String(length=350), nullable=True),
    sa.Column('pagamento', sa.String(length=80), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('taxa_entrega', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('tempo_estimado_min', sa.Integer(), nullable=True),
    sa.Column('tempo_estimado_max', sa.Integer(), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(), nullable=True),
    sa.Column('em_preparo_em', sa.DateTime(), nullable=True),
    sa.Column('pronto_em', sa.DateTime(), nullable=True),
    sa.Column('saiu_entrega_em', sa.DateTime(), nullable=True),
    sa.Column('entregue_em', sa.DateTime(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_request_id', name='uq_pedido_tenant_request'),
    sa.UniqueConstraint('tenant_id', 'numero', name='uq_pedido_tenant_numero')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_comanda_aberta'), ['comanda_aberta'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_mesa'), ['mesa'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_pedido_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_telefone'), ['telefone'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pedido_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco_base', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_item_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_item_produto_id'), ['produto_id'], unique=False)

    op.create_table('pedido_item_adicional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_item_id', sa.Integer(), nullable=False),
    sa.Column('adicional_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['adicional_id'], ['adicional.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_item_id'], ['pedido_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_item_adicional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_item_adicional_adicional_id'), ['adicional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_item_adicional_pedido_item_id'), ['pedido_item_id'], unique=False)

    # server_default é obrigatório aqui: a tabela já tem tenants, e coluna
    # NOT NULL sem default no BANCO é recusada (o default=0 do modelo é só do
    # Python, o autogenerate não o traduz). Os tenants existentes ficam com
    # salão zerado, ou seja, sem atender mesa até configurarem.
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_mesas', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(
            sa.Column('tempo_estimado_min', sa.Integer(), nullable=False, server_default='40')
        )
        batch_op.add_column(
            sa.Column('tempo_estimado_max', sa.Integer(), nullable=False, server_default='60')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('tempo_estimado_max')
        batch_op.drop_column('tempo_estimado_min')
        batch_op.drop_column('qtd_mesas')

    with op.batch_alter_table('pedido_item_adicional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_item_adicional_pedido_item_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_item_adicional_adicional_id'))

    op.drop_table('pedido_item_adicional')
    with op.batch_alter_table('pedido_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_item_produto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_item_pedido_id'))

    op.drop_table('pedido_item')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_telefone'))
        batch_op.drop_index(batch_op.f('ix_pedido_status'))
        batch_op.drop_index(batch_op.f('ix_pedido_public_token'))
        batch_op.drop_index(batch_op.f('ix_pedido_mesa'))
        batch_op.drop_index(batch_op.f('ix_pedido_comanda_aberta'))

    op.drop_table('pedido')
    # ### end Alembic commands ###
