"""recursos liberados por plano

Revision ID: 6c19ad6ef5bc
Revises: 217eb945355e
Create Date: 2026-08-13 16:13:57.791166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c19ad6ef5bc'
down_revision = '217eb945355e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recursos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano', schema=None) as batch_op:
        batch_op.drop_column('recursos')

    # ### end Alembic commands ###
