"""caixa do turno, loja aberta e tempo de retirada

Revision ID: 7fc908913742
Revises: 8e446c182992
Create Date: 2026-08-24 07:37:24.823989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc908913742'
down_revision = '8e446c182992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(), nullable=False),
    sa.Column('aberto_por', sa.String(length=80), nullable=True),
    sa.Column('valor_inicial', sa.Float(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('fechado_por', sa.String(length=80), nullable=True),
    sa.Column('valor_contado', sa.Float(), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE', name='fk_caixa_tenant'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caixa_aberto_em'), ['aberto_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_caixa_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_caixa_aberto_por_tenant', ['tenant_id'], unique=True, sqlite_where=sa.text('fechado_em IS NULL'), postgresql_where=sa.text('fechado_em IS NULL'))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        # server_default: a tabela ja tem restaurantes, e eles nao podem amanhecer
        # fechados so porque a coluna nasceu. Quem ja vende continua vendendo.
        batch_op.add_column(
            sa.Column('loja_aberta', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column('tempo_retirada_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_retirada_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('tempo_retirada_max')
        batch_op.drop_column('tempo_retirada_min')
        batch_op.drop_column('loja_aberta')

    with op.batch_alter_table('caixa', schema=None) as batch_op:
        batch_op.drop_index('uq_caixa_aberto_por_tenant', sqlite_where=sa.text('fechado_em IS NULL'), postgresql_where=sa.text('fechado_em IS NULL'))
        batch_op.drop_index(batch_op.f('ix_caixa_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_caixa_aberto_em'))

    op.drop_table('caixa')
    # ### end Alembic commands ###
