"""pagamento pix por pedido e chave do restaurante

Revision ID: 85476076628e
Revises: e363eab8eb65
Create Date: 2026-08-21 07:38:34.978274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85476076628e'
down_revision = 'e363eab8eb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('brcode', sa.Text(), nullable=True),
    sa.Column('txid', sa.String(length=30), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('confirmado_por', sa.String(length=80), nullable=True),
    sa.Column('erro', sa.String(length=500), nullable=True),
    sa.Column('resposta_bruta', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id', name='uq_pagamento_pedido')
    )
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamento_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_referencia'), ['referencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamento_txid'), ['txid'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_chave', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('pix_recebedor', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('pix_cidade', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('pix_cidade')
        batch_op.drop_column('pix_recebedor')
        batch_op.drop_column('pix_chave')

    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamento_txid'))
        batch_op.drop_index(batch_op.f('ix_pagamento_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pagamento_status'))
        batch_op.drop_index(batch_op.f('ix_pagamento_referencia'))
        batch_op.drop_index(batch_op.f('ix_pagamento_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_pagamento_criado_em'))

    op.drop_table('pagamento')
    # ### end Alembic commands ###
