"""relogios do salao: ultimo consumo e conta pedida

Revision ID: 8e446c182992
Revises: 7989e7a6b809
Create Date: 2026-08-22 08:45:42.360281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e446c182992'
down_revision = '7989e7a6b809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_consumo_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('conta_pedida_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('conta_pedida_em')
        batch_op.drop_column('ultimo_consumo_em')

    # ### end Alembic commands ###
