"""log de auditoria

Revision ID: 9e04a8f0bd1f
Revises: b362223866ef
Create Date: 2026-08-21 15:51:13.207566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e04a8f0bd1f'
down_revision = 'b362223866ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('tenant_slug', sa.String(length=50), nullable=True),
    sa.Column('ator', sa.String(length=80), nullable=False),
    sa.Column('ator_tipo', sa.String(length=20), nullable=False),
    sa.Column('acao', sa.String(length=40), nullable=False),
    sa.Column('alvo', sa.String(length=120), nullable=True),
    sa.Column('detalhes', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_tenant_slug'), ['tenant_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_tenant_slug'))
        batch_op.drop_index(batch_op.f('ix_auditoria_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_auditoria_acao'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
