"""contatos de interesse na pagina do produto

Revision ID: a90405bf07e5
Revises: 7fc908913742
Create Date: 2026-08-25 14:29:01.123897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90405bf07e5'
down_revision = '7fc908913742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interesse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('mensagem', sa.String(length=1000), nullable=True),
    sa.Column('plano', sa.String(length=80), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('anotacao', sa.String(length=1000), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interesse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interesse_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_interesse_situacao'), ['situacao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interesse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interesse_situacao'))
        batch_op.drop_index(batch_op.f('ix_interesse_criado_em'))

    op.drop_table('interesse')
    # ### end Alembic commands ###
