"""cobranca com link de pagamento e cliente no asaas

Revision ID: b362223866ef
Revises: d7e4c876b207
Create Date: 2026-08-21 15:08:00.270194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b362223866ef'
down_revision = 'd7e4c876b207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cobranca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_pagamento', sa.String(length=500), nullable=True))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asaas_customer_id', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenant_asaas_customer_id'), ['asaas_customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_asaas_customer_id'))
        batch_op.drop_column('asaas_customer_id')

    with op.batch_alter_table('cobranca', schema=None) as batch_op:
        batch_op.drop_column('url_pagamento')

    # ### end Alembic commands ###
