"""avisos de whatsapp por pedido e config por tenant

Revision ID: bdd821a4c858
Revises: 484a46a8d0f4
Create Date: 2026-08-21 09:39:38.739007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd821a4c858'
down_revision = '484a46a8d0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provedor', sa.String(length=20), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.String(length=700), nullable=True),
    sa.Column('id_externo', sa.String(length=120), nullable=True),
    sa.Column('enviada_em', sa.DateTime(), nullable=True),
    sa.Column('enviada_por', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id', 'evento', name='uq_notificacao_pedido_evento')
    )
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacao_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacao_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacao_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        # server_default é obrigatório aqui: a tabela `tenant` já tem linhas no
        # servidor, e uma coluna NOT NULL sem valor de partida faz o ALTER TABLE
        # falhar no meio da atualização. "link" é o modo grátis, que é o certo
        # para quem nunca configurou nada.
        batch_op.add_column(
            sa.Column(
                'whatsapp_provedor', sa.String(length=20), nullable=False, server_default='link'
            )
        )
        batch_op.add_column(sa.Column('whatsapp_phone_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_modelos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_modelos')
        batch_op.drop_column('whatsapp_token')
        batch_op.drop_column('whatsapp_phone_id')
        batch_op.drop_column('whatsapp_provedor')

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacao_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notificacao_status'))
        batch_op.drop_index(batch_op.f('ix_notificacao_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_notificacao_criado_em'))

    op.drop_table('notificacao')
    # ### end Alembic commands ###
