"""financeiro: despesas e receitas avulsas

Revision ID: c329221dfe2f
Revises: 413201f851c5
Create Date: 2026-08-14 09:30:44.520766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c329221dfe2f'
down_revision = '413201f851c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('paga', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('observacao', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesa_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesa_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesa_paga'), ['paga'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesa_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('receita_avulsa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('observacao', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receita_avulsa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receita_avulsa_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_receita_avulsa_data_registro'), ['data_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_receita_avulsa_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita_avulsa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receita_avulsa_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_receita_avulsa_data_registro'))
        batch_op.drop_index(batch_op.f('ix_receita_avulsa_categoria'))

    op.drop_table('receita_avulsa')
    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesa_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_despesa_paga'))
        batch_op.drop_index(batch_op.f('ix_despesa_data_vencimento'))
        batch_op.drop_index(batch_op.f('ix_despesa_categoria'))

    op.drop_table('despesa')
    # ### end Alembic commands ###
