"""schema inicial

Revision ID: e3f0dcfee1c2
Revises: 
Create Date: 2026-08-11 16:01:36.979296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f0dcfee1c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_admin_username'), ['username'], unique=True)

    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=120), nullable=False),
    sa.Column('razao_social', sa.String(length=160), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('email_contato', sa.String(length=160), nullable=False),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('plano', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_termina_em', sa.DateTime(), nullable=True),
    sa.Column('assinatura_provider', sa.String(length=30), nullable=True),
    sa.Column('assinatura_id_externo', sa.String(length=120), nullable=True),
    sa.Column('proxima_cobranca_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_assinatura_id_externo'), ['assinatura_id_externo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_status'), ['status'], unique=False)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_usuario_tenant_username')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_tenant_id'))

    op.drop_table('usuario')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_tenant_id'))

    op.drop_table('produto')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_status'))
        batch_op.drop_index(batch_op.f('ix_tenant_slug'))
        batch_op.drop_index(batch_op.f('ix_tenant_assinatura_id_externo'))

    op.drop_table('tenant')
    with op.batch_alter_table('platform_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_admin_username'))

    op.drop_table('platform_admin')
    # ### end Alembic commands ###
