"""logo e cor de marca por tenant

Revision ID: fb6acdd91454
Revises: c329221dfe2f
Create Date: 2026-08-14 12:14:20.567461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6acdd91454'
down_revision = 'c329221dfe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cor_marca', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('cor_marca')
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
